export const countryData = {
    data: [
        {
            name: 'Afghanistan - AF',
            code: 'AF',
            alias: 'afghanistan|阿富汗|afganistán|Афганистан|afganistan|afeganistão|アフガニスタン|아프가니스탄|AFG|AF',
            phone: '93',
        },
        {
            name: 'Aland Islands - AX',
            code: 'AX',
            alias: 'aland islands|阿富汗|islas aland|Аландские острова|isole aland|aland-inseln|wyspy alandzkie|Îles aland|ilhas aland|オーランド諸島|alandeilanden|aland adaları|올란드제도|ALA|AX',
        },
        {
            name: 'Albania - AL',
            code: 'AL',
            alias: 'albania|阿尔巴尼亚|Албания|albanien|albanie|albânia|アルバニア|albanië|arnavutluk|알바니아|ALB|AL',
            phone: '355',
        },
        {
            name: 'Algeria - DZ',
            code: 'DZ',
            alias: 'algeria|阿尔及利亚|Алжир|algerien|algieria|algérie|argélia|アルジェリア|algerije|cezayir|알제리|DZA|DZ',
            phone: '213',
        },
        {
            name: 'American Samoa - AS',
            code: 'AS',
            alias: 'american samoa|美国 萨摩亚|samoa americana|Американское Самоа|samoa americane|amerikanisch samoa|samoa amerykańskie|samoa américaines|アメリカ領サモア|amerikaans samoa|amerika samoası|아메리칸 사모아|ASM|AS',
            phone: '1-684',
        },
        {
            name: 'Andorra - AD',
            code: 'AD',
            alias: 'andorra|安道尔|Андорра|andora|andorre|アンドラ|안도라|AND|AD',
            phone: '376',
        },
        {
            name: 'Angola - AO',
            code: 'AO',
            alias: 'angola|安哥拉|Ангола|アンゴラ|앙골라|AGO|AO',
            phone: '244',
        },
        {
            name: 'Anguilla - AI',
            code: 'AI',
            alias: 'anguilla|安圭拉|anguila|Ангилья|アングィラ|앵귈라|AIA|AI',
            phone: '1-264',
        },
        {
            name: 'Antarctica - AQ',
            code: 'AQ',
            alias: 'antarctica|南极洲|antártida|Антарктика|antartide|antarktis|antarktyda|antarctique|antártica|南極|antarktika|남극대륙|ATA|AQ',
            phone: '672',
        },
        {
            name: 'Antigua & Barbuda - AG',
            code: 'AG',
            alias: 'antigua & barbuda|antigua y barbuda|Антигуа и Барбуда|antigua ve barbuda|アンティグア＆バーブーダ|antigua e barbuda|앤티가바부다|antiqua & barbuda|antígua e barbuda|antigua et barbuda|antigua und barbuda|antigua en barbuda|antigua i barbuda|安提瓜和巴布达|ATG|AG',
            phone: '1-268',
        },
        {
            name: 'Argentina - AR',
            code: 'AR',
            alias: 'argentina|阿根廷|Аргентина|argentinien|argentyna|argentine|アルゼンチン|argentinië|arjantin|아르헨티나|ARG|AR',
            phone: '54',
        },
        {
            name: 'Armenia - AM',
            code: 'AM',
            alias: 'armenia|亚美尼亚|Армения|armenien|arménie|armênia|アルメニア|armenië|ermenistan|아르메니아|ARM|AM',
            phone: '374',
        },
        {
            name: 'Aruba - AW',
            code: 'AW',
            alias: 'aruba|阿鲁巴|Аруба|アルバ|ABW|AW',
            phone: '297',
        },
        {
            name: 'Australia - AU',
            code: 'AU',
            alias: 'australia|澳大利亚|Австралия|australien|australie|オーストラリア|austrália|australië|avustralya|호주|AUS|AU',
            phone: '61',
        },
        {
            name: 'Austria - AT',
            code: 'AT',
            alias: 'austria|奥地利|Австрия|Österreich|autriche|オーストリア|Áustria|oostenrijk|avusturya|오스트리아|AUT|AT',
            phone: '43',
        },
        {
            name: 'Azerbaijan - AZ',
            code: 'AZ',
            alias: 'azerbaijan|阿塞拜疆|azerbaiyán|Азербайджан|azerbaigian|aserbaidschan|azerbejdżan|azerbaïdjan|アゼルバイジャン|azerbaijão|azerbeidjzan|azerbaycan|아제르바이잔|AZE|AZ',
            phone: '994',
        },
        {
            name: 'Bahamas - BS',
            code: 'BS',
            alias: "bahamas|巴哈马|Багамские острова|bahamy|バハマ|bahama's|bahamalar|바하마|BHS|BS",
            phone: '1-242',
        },
        {
            name: 'Bahrain - BH',
            code: 'BH',
            alias: 'bahrain|巴林|baréin|Бахрейн|bahrajn|bahrein|バーレーン|barém|bahreyn|바레인|BHR|BH',
            phone: '973',
        },
        {
            name: 'Bangladesh - BD',
            code: 'BD',
            alias: 'bangladesh|孟加拉国|Бангладеш|bangladesch|bangladesz|バングラデシュ|bangladeş|방글라데시|BGD|BD',
            phone: '880',
        },
        {
            name: 'Barbados - BB',
            code: 'BB',
            alias: 'barbados|巴巴多斯|Барбадос|barbades|バルバドス|BRB|BB',
            phone: '1-246',
        },
        {
            name: 'Belarus - BY',
            code: 'BY',
            alias: 'belarus|白俄罗斯|bielorrusia|Беларусь|bielorussia|weißrussland|białoruś|biélorussie|ベラルーシ|beyaz rusya|wit-rusland|BLR|BY',
            phone: '375',
        },
        {
            name: 'Belgium - BE',
            code: 'BE',
            alias: 'belgium|比利时|belgica|Бельгия|belgio|belgien|belgia|belgique|ベルギー|bélgica|belçika|belgië|벨기에|BEL|BE',
            phone: '32',
        },
        {
            name: 'Belize - BZ',
            code: 'BZ',
            alias: 'belize|伯利兹|belice|Белиз|ベリーズ|BLZ|BZ',
            phone: '501',
        },
        {
            name: 'Benin - BJ',
            code: 'BJ',
            alias: 'benin|贝宁|benín|Бенин|bénin|ベナン|베닌|BEN|BJ',
            phone: '229',
        },
        {
            name: 'Bermuda - BM',
            code: 'BM',
            alias: 'bermuda|百慕达群岛|bermudas|Бермудские острова|bermudy|bermudes|バミューダ|버뮤다|BMU|BM',
            phone: '1-441',
        },
        {
            name: 'Bhutan - BT',
            code: 'BT',
            alias: 'bhutan|不丹|bután|Бутан|bhoutan|butão|ブータン|BTN|BT',
            phone: '975',
        },
        {
            name: 'Bolivia - BO',
            code: 'BO',
            alias: 'bolivia|玻利维亚|Боливия|bolivien|boliwia|bolivie|bolívia|bolivya|ボリビア|BOL|BO',
            phone: '591',
        },
        {
            name: 'Bonaire, St Eustatius and Saba - BQ',
            code: 'BQ',
            alias: 'bonaire, st eustatius and saba|bonaire, san eustaquio y saba|Бонэйр, Синт-Эстатиус и Саба|bonaire, st eustatius ve saba|ボネール、シント・ユースタティウス、およびサバ|bonaire, sint eustatius e saba|보나이러, 세인트 유스타티우스 사바|bonaire, st eustatius och saba|bonaire, st. eustache et saba|bonaire, santo eustáquio e saba|bonaire, st. eustatius und saba|bonaire, sint eustatius en saba|bonaire, saint eustatiusi saba|博奈尔岛，圣尤斯达蒂斯和萨巴|BES|BQ',
        },
        {
            name: 'Bosnia and Herzegovina - BA',
            code: 'BA',
            alias: 'bosnia and herzegovina|波斯尼亚 - 黑塞哥维那|bosnia-herzegovina|Босния и Герцеговина|bosnia ed erzegovina|bosnien und herzegovina|bośnia i hercegowina|bosnie et herzégovine|bósnia e herzegovina|bosna-hersek|ボスニア・ヘルツェゴビナ|BIH|BA',
            phone: '387',
        },
        {
            name: 'Botswana - BW',
            code: 'BW',
            alias: 'botswana|博茨瓦纳|Ботсвана|botsuana|ボツワナ|BWA|BW',
            phone: '267',
        },
        {
            name: 'Bouvet Island - BV',
            code: 'BV',
            alias: 'bouvet island|布维岛|islas bouvet|Остров Буве|isola di bouvet|bouvet insel|wyspa bouveta|Île bouvet|ilha bouvet|bouveteiland|ブーベ島|BVT|BV',
        },
        {
            name: 'Brazil - BR',
            code: 'BR',
            alias: 'brazil|巴西|brasil|Бразилия|brasile|brasilien|brazylia|brésil|brezilya|brazilië|ブラジル|브라질|BRA|BR',
            phone: '55',
        },
        {
            name: 'British Indian Ocean Territory - IO',
            code: 'IO',
            alias: "british indian ocean territory|英属印度洋领地|territorio británico del océano Índico|Британская Территория в Индийском Океане|territori britannici dell'oceano indiano|britisches territorium im indischen ozean|brytyjskie terytorium oceanu indyjskiego|territoire britannique de l'océan indien|território britânico do oceano Índico|britanya hint okyanusu toprakları|brits indische oceaanterritorium|イギリス領インド洋地域|IOT|IO",
            phone: '246',
        },
        {
            name: 'Brunei Darussalam - BN',
            code: 'BN',
            alias: 'brunei darussalam|文莱达鲁萨兰国|Бруней Даруссалам|brunei darüsselam|ブルネイ・ダルサラーム|BRN|BN',
            phone: '673',
        },
        {
            name: 'Bulgaria - BG',
            code: 'BG',
            alias: 'bulgaria|保加利亚|Болгария|bulgarien|bułgaria|bulgarie|bulgária|bulgaristan|bulgarije|ブルガリア|불가리아|BGR|BG',
            phone: '359',
        },
        {
            name: 'Burkina Faso - BF',
            code: 'BF',
            alias: 'burkina faso|布基纳法索|Буркина Фасо|ブルキナファソ|BFA|BF',
            phone: '226',
        },
        {
            name: 'Burundi - BI',
            code: 'BI',
            alias: 'burundi|蒲隆地|Бурунди|ブルンジ|BDI|BI',
            phone: '257',
        },
        {
            name: 'Cambodia - KH',
            code: 'KH',
            alias: 'cambodia|柬埔寨|camboya|Камбоджа|kambodscha|cambogia|kambodża|cambodge|camboja|kamboçya|カンボジア|cambodja|캄보디아|KHM|KH',
            phone: '855',
        },
        {
            name: 'Cameroon - CM',
            code: 'CM',
            alias: 'cameroon|喀麦隆|camerún|Камерун|kamerun|camerun|cameroun|camarões|カメルーン|kameroen|CMR|CM',
            phone: '237',
        },
        {
            name: 'Canada - CA',
            code: 'CA',
            alias: 'canada|加拿大|canadá|Канада|kanada|カナダ|캐나다|CAN|CA',
            phone: '1',
        },
        {
            name: 'Cape Verde - CV',
            code: 'CV',
            alias: 'cape verde|佛得角|cabo verde|Кабо-Верде|kapverde|capo verde|republika zielonego przylądka|cap-vert|yeşil burun|カーボベルデ|kaapverdië|cap verde|카보베르데|CPV|CV',
            phone: '238',
        },
        {
            name: 'Cayman Islands - KY',
            code: 'KY',
            alias: 'cayman islands|开曼群岛|islas caimán|Каймановы острова|cayman inseln|isole cayman|kajmany|Îles caïmans|ilhas cayman|keyman adaları|ケイマン諸島|kaaimaneilanden|CYM|KY',
            phone: '1-345',
        },
        {
            name: 'Central African Republic - CF',
            code: 'CF',
            alias: 'central african republic|中非共和国|república centroafricana|Центральноафриканская Республика|zentralafrikanische republik|repubblica centrafricana|republika Środkowoafrykańska|république centrafricaine|república centro-africana|orta afrika cumhuriyeti|中央アフリカ共和国|centraal-afrikaanse republiek|CAF|CF',
            phone: '236',
        },
        {
            name: 'Chad - TD',
            code: 'TD',
            alias: 'chad|乍得|Чад|ciad|czad|tchad|chade|Çad|チャド|tsjaad|TCD|TD',
            phone: '235',
        },
        {
            name: 'Chile - CL',
            code: 'CL',
            alias: 'chile|智利|Чили|cile|chili|Şili|チリ|칠레|CHL|CL',
            phone: '56',
        },
        {
            name: 'China - CN',
            code: 'CN',
            alias: 'china|中国|Китай|cina|chiny|chine|Çin|kina|중국|CHN|CN',
            phone: '86',
        },
        {
            name: 'Christmas Island - CX',
            code: 'CX',
            alias: 'christmas island|圣诞岛|isla de navidad|Остров Рождества|weihnachtsinsel|isola di natale|wyspa bożego narodzenia|Île christmas|ilha do natal|christmas adası|クリスマス島|kersteiland|CXR|CX',
            phone: '61',
        },
        {
            name: 'Cocos (K) Island - CC',
            code: 'CC',
            alias: 'cocos (k) island|isla cocos (k)|Кокосовые острова Килинг|cocos (k) adası|코코스 (k) 섬|isole cocos (keeling)|kokosöarna|Îles cocos (k)|ilha cocos (k)|cocos (k) insel|cocoseiland|wyspa kokosowa (k)|ココス(k)諸島|CCK|CC',
            phone: '61',
        },
        {
            name: 'Colombia - CO',
            code: 'CO',
            alias: 'colombia|哥伦比亚|Колумбия|kolumbien|kolumbia|colombie|colômbia|コロンビア|kolombiya|콜롬비아|COL|CO',
            phone: '57',
        },
        {
            name: 'Comoros - KM',
            code: 'KM',
            alias: 'comoros|科摩罗|Коморы|comore|komory|comores|コモロ|COM|KM',
            phone: '269',
        },
        {
            name: 'Congo - CG',
            code: 'CG',
            alias: 'congo|刚果共和国|Конго|kongo|コンゴ|COG|CG',
            phone: '242',
        },
        {
            name: 'Cook Islands - CK',
            code: 'CK',
            alias: 'cook islands|库克群岛|cook (islas)|Острова Кука|cook inseln|isole cook|wyspy cooka|Îles cook|ilhas cook|クック諸島|cook eilanden|COK|CK',
            phone: '682',
        },
        {
            name: 'Costa Rica - CR',
            code: 'CR',
            alias: 'costa rica|哥斯达黎加|Коста-Рика|kostaryka|コスタリカ|kosta rika|코스타리카|CRI|CR',
            phone: '506',
        },
        {
            name: 'Ivory Coast - CI',
            code: 'CI',
            alias: "ivory coast|elfenbeinküste|côte d'ivoire|Кот-д'Ивуар|코트디부아르|wybrzeże kości słoniowej|costa de marfil|ivoorkust|fildişi sahili|elfenbenskusten|コートジボワール|costa do marfim|costa d'avorio|象牙海岸|CIV|CI",
            phone: '225',
        },
        {
            name: 'Croatia - HR',
            code: 'HR',
            alias: 'croatia|克罗地亚|croacia|Хорватия|kroatien|croazia|chorwacja|croatie|croácia|クロアチア|kroatië|크로아티아|HRV|HR',
            phone: '385',
        },
        {
            name: 'Cuba - CU',
            code: 'CU',
            alias: 'cuba|古巴|Куба|kuba|キューバ|쿠바|CUB|CU',
            phone: '53',
        },
        {
            name: 'Curacao - CW',
            code: 'CW',
            alias: 'curacao|库拉索|curasao|Кюрасао|curaçao|キュラソー|큐라 소|CUW|CW',
            phone: '599',
        },
        {
            name: 'Cyprus - CY',
            code: 'CY',
            alias: 'cyprus|塞浦路斯|chipre|Кипр|zypern|cipro|cypr|chypre|キプロス|kıbrıs|키프로스|CYP|CY',
            phone: '357',
        },
        {
            name: 'Czech Republic - CZ',
            code: 'CZ',
            alias: 'czech republic|捷克共和国|república checa|Чешская Республика|tschechische republik|repubblica ceca|czechy|république tchèque|チェコ共和国|tsjechische republiek|CZE|CZ',
            phone: '420',
        },
        {
            name: 'Democratic Republic of Congo - CD',
            code: 'CD',
            alias: 'democratic republic of congo|república democrática del congo|Демократическая Республика Конго|kongo demokratik cumhuriyeti|コンゴ民主共和国|콩고민주공화국|repubblica democratica del congo|kongo|république démocratique du congo|república democrática do congo|demokratische republik kongo|democratische republiek congo|demokratyczna republika konga|刚果民主共和国|COD|CD',
            phone: '243',
        },
        {
            name: 'Denmark - DK',
            code: 'DK',
            alias: 'denmark|丹麦|dinamarca|Дания|dänemark|danimarca|dania|danemark|デンマーク|denemarken|덴마크|DNK|DK',
            phone: '45',
        },
        {
            name: 'Djibouti - DJ',
            code: 'DJ',
            alias: 'djibouti|吉布提|yibuti|Джибути|dschibuti|gibuti|dżibuti|djibuti|ジブチ|cibuti|지부티|DJI|DJ',
            phone: '253',
        },
        {
            name: 'Dominica - DM',
            code: 'DM',
            alias: 'dominica|多米尼克|Доминика|dominika|dominique|ドミニカ|DMA|DM',
            phone: '1-767',
        },
        {
            name: 'Dominican Republic - DO',
            code: 'DO',
            alias: 'dominican republic|多米尼加共和国|república dominicana|Доминиканская Республика|dominikanische republik|repubblica dominicana|dominikana|république dominicaine|ドミニカ共和国|dominicaanse republiek|도미니카 공화국|DOM|DO',
            phone: '1-809, 1-829, 1-849',
        },
        {
            name: 'East Timor - TL',
            code: 'TL',
            alias: 'east timor|timor oriental|Восточный Тимор|doğu timor|東チモール|동티모르|timor est|Öst timor|timor leste|osttimor|oost-timor|timor wschodni|东帝汶|TLS|TL',
            phone: '670',
        },
        {
            name: 'Ecuador - EC',
            code: 'EC',
            alias: 'ecuador|厄瓜多尔|Эквадор|ekwador|Équateur|equador|エクアドル|ECU|EC',
            phone: '593',
        },
        {
            name: 'Egypt - EG',
            code: 'EG',
            alias: 'egypt|埃及|egipto|Египет|Ägypten|egitto|egipt|Égypte|egito|エジプト|egypte|mısır|egypten|이집트|EGY|EG',
            phone: '20',
        },
        {
            name: 'El Salvador - SV',
            code: 'SV',
            alias: 'el salvador|萨尔瓦多|Сальвадор|salwador|SLV|SV',
            phone: '503',
        },
        {
            name: 'Equatorial Guinea - GQ',
            code: 'GQ',
            alias: 'equatorial guinea|赤道几内亚|guinea ecuatorial|Экваториальная Гвинея|Äquatorial guinea|guinea equatoriale|gwinea równikowa|guinée Équatoriale|guiné equatorial|赤道ギニア|equatoriaal-guinee|GNQ|GQ',
            phone: '240',
        },
        {
            name: 'Eritrea - ER',
            code: 'ER',
            alias: 'eritrea|厄立特里亚|Эритрея|erytrea|Érythrée|eritréia|エリトリア|ERI|ER',
            phone: '291',
        },
        {
            name: 'Estonia - EE',
            code: 'EE',
            alias: 'estonia|爱沙尼亚|Эстония|estland|estonie|estônia|エストニア|에스토니아|EST|EE',
            phone: '372',
        },
        {
            name: 'Ethiopia - ET',
            code: 'ET',
            alias: 'ethiopia|埃塞俄比亚|etiopía|Эфиопия|Äthiopien|etiopia|Éthiopie|etiópia|エチオピア|ethiopië|etiyopya|etiopien|에티오피아|ETH|ET',
            phone: '251',
        },
        {
            name: 'Falkland Islands (Malvinas) - FK',
            code: 'FK',
            alias: 'falkland islands (malvinas)|福克蘭群島|falkland (islas)|Фолклендские острова|falkland inseln (malvinas)|isole falkland (malvine)|falklandy (malwiny)|Îles falkland (malouines)|ilhas malvinas|フォークランド諸島（マルビナス）|falklandeilanden (malvinas)|FLK|FK',
            phone: '500',
        },
        {
            name: 'Faroe Islands - FO',
            code: 'FO',
            alias: 'faroe islands|法罗群岛|feroe (islas)|Фарерские острова|faröer inseln|isole faroe|wyspy owcze|Îles féroé|ilhas faroe|フェロー諸島|faroer eilanden|FRO|FO',
            phone: '298',
        },
        {
            name: 'Fiji - FJ',
            code: 'FJ',
            alias: 'fiji|斐济|fiyi|Фиджи|figi|fidżi|fidji|フィジー|FJI|FJ',
            phone: '679',
        },
        {
            name: 'Finland - FI',
            code: 'FI',
            alias: 'finland|芬兰|finlandia|Финляндия|finnland|finlande|finlândia|フィンランド|핀란드|FIN|FI',
            phone: '358',
        },
        {
            name: 'France - FR',
            code: 'FR',
            alias: 'france|法国|francia|Франция|frankreich|francja|frança|フランス|frankrijk|fransa|프랑스|FRA|FR',
            phone: '33',
        },
        {
            name: 'French Guiana - GF',
            code: 'GF',
            alias: 'french guiana|法屬圭亞那|guayana francesa|Гвиана|französisch guiana|guiana francese|gujana francuska|guyane française|guiana francesa|フランス領ギアナ|frans-guyana|GUF|GF',
        },
        {
            name: 'French Polynesia - PF',
            code: 'PF',
            alias: 'french polynesia|法属波利尼西亚|polinesia francesa|Французская Полинезия|französisch polynesien|polinesia francese|polinezja francuska|polynésie française|polinésia francesa|フランス領ポリネシア|frans-polynesië|PYF|PF',
            phone: '689',
        },
        {
            name: 'French West Indies - TF',
            code: 'TF',
            alias: 'french west indies|antillas francesas|Французская Вест-Индия|fransız batı hint adaları|フランス領西インド諸島|프랑스령 서인도제도|antille francesi|franska västindien|antilles françaises|antilhas francesas|französisch westindien|franse antillen|antyle francuskie|法属西印度群岛|ATF|TF',
        },
        {
            name: 'Gabon - GA',
            code: 'GA',
            alias: 'gabon|加蓬|gabón|Габон|gabun|gabão|ガボン|가봉|GAB|GA',
            phone: '241',
        },
        {
            name: 'Gambia - GM',
            code: 'GM',
            alias: 'gambia|冈比亚|Гамбия|gambie|gâmbia|ガンビア|GMB|GM',
            phone: '220',
        },
        {
            name: 'Georgia - GE',
            code: 'GE',
            alias: 'georgia|格鲁吉亚|Грузия|georgien|gruzja|géorgie|ジョージア|georgië|gürcistan|조지아|GEO|GE',
            phone: '995',
        },
        {
            name: 'Germany - DE',
            code: 'DE',
            alias: 'germany|德国|alemania|Германия|deutschland|germania|niemcy|allemagne|alemanha|ドイツ|duitsland|독일|almanya|tyskland|DEU|DE',
            phone: '49',
        },
        {
            name: 'Ghana - GH',
            code: 'GH',
            alias: 'ghana|加纳|Гана|gana|ガーナ|GHA|GH',
            phone: '233',
        },
        {
            name: 'Gibraltar - GI',
            code: 'GI',
            alias: 'gibraltar|直布罗陀|Гибралтар|gibilterra|ジブラルタル|GIB|GI',
            phone: '350',
        },
        {
            name: 'Greece - GR',
            code: 'GR',
            alias: 'greece|希腊|grecia|Греция|griechenland|grecja|grèce|grécia|ギリシャ|griekenland|그리스|GRC|GR',
            phone: '30',
        },
        {
            name: 'Greenland - GL',
            code: 'GL',
            alias: 'greenland|格陵兰|groenlandia|Гренландия|grönland|grenlandia|groenland|groelândia|グリーンランド|GRL|GL',
            phone: '299',
        },
        {
            name: 'Grenada - GD',
            code: 'GD',
            alias: 'grenada|格瑞那達|granada|Гренада|grenade|グレナダ|GRD|GD',
            phone: '1-473',
        },
        {
            name: 'Guadeloupe - GP',
            code: 'GP',
            alias: 'guadeloupe|瓜德罗普岛|guadalupe|Гваделупа|guadalupa|gwadelupa|グアドループ|GLP|GP',
        },
        {
            name: 'Guam - GU',
            code: 'GU',
            alias: 'guam|关岛|Гуам|グアム|GUM|GU',
            phone: '1-671',
        },
        {
            name: 'Guatemala - GT',
            code: 'GT',
            alias: 'guatemala|危地马拉 (瓜地馬拉)|Гватемала|gwatemala|グアテマラ|GTM|GT',
            phone: '502',
        },
        {
            name: 'Guernsey - GG',
            code: 'GG',
            alias: 'guernsey|根西岛|Гернси|guernesey|ガーンジー|건지|GGY|GG',
            phone: '44-1481',
        },
        {
            name: 'Guinea - GN',
            code: 'GN',
            alias: 'guinea|几内亚|Гвинея|gwinea|guinée|guiné|ギニア|GIN|GN',
            phone: '224',
        },
        {
            name: 'Guinea-Bissau - GW',
            code: 'GW',
            alias: 'guinea-bissau|几内亚比绍|Гвинея-Бисау|gwinea bissau|guinée bissau|guiné-bissau|ギニアビサウ|GNB|GW',
            phone: '245',
        },
        {
            name: 'Guyana - GY',
            code: 'GY',
            alias: 'guyana|圭亚那|Гайана|gujana|guiana|GUY|GY',
            phone: '592',
        },
        {
            name: 'Haiti - HT',
            code: 'HT',
            alias: 'haiti|海地|haití|Гаити|haïti|HTI|HT',
            phone: '509',
        },
        {
            name: 'Heard Island and McDonald Islands - HM',
            code: 'HM',
            alias: 'heard island and mcdonald islands|赫德岛和麦当劳群岛|Остров Херд и острова Макдональд|heard insel und mcdonald inseln|isole heard e mcdonald|wyspy heard i mcdonalda|Îles heard et mcdonald|heard eiland en mcdonald eilanden|ilha heard e ilhas mcdonald|heard adası ve mcdonald adaları|HMD|HM',
        },
        {
            name: 'Honduras - HN',
            code: 'HN',
            alias: 'honduras|洪都拉斯|Гондурас|HND|HN',
            phone: '504',
        },
        {
            name: 'Hong Kong - HK',
            code: 'HK',
            alias: 'hong kong|香港|Гонконг|hongkong|홍콩|HKG|HK',
            phone: '852',
        },
        {
            name: 'Hungary - HU',
            code: 'HU',
            alias: 'hungary|匈牙利|hungría|Венгрия|ungarn|ungheria|węgry|hongrie|hongarije|hungria|ハンガリー|헝가리|HUN|HU',
            phone: '36',
        },
        {
            name: 'Iceland - IS',
            code: 'IS',
            alias: 'iceland|冰岛|islandia|Исландия|island|islanda|islande|ijsland|islândia|ISL|IS',
            phone: '354',
        },
        {
            name: 'India - IN',
            code: 'IN',
            alias: 'india|印度|Индия|indien|indie|inde|Índia|hindistan|인도|インド|IND|IN',
            phone: '91',
        },
        {
            name: 'Indonesia - ID',
            code: 'ID',
            alias: 'indonesia|印度尼西亚, 印尼|Индонезия|indonesien|indonezja|indonésie|indonésia|indonesië|インドネシア|인도네시아|IDN|ID',
            phone: '62',
        },
        {
            name: 'Iran - IR',
            code: 'IR',
            alias: 'iran|伊朗|Иран|irã|イラン|이란|IRN|IR',
            phone: '98',
        },
        {
            name: 'Iraq - IQ',
            code: 'IQ',
            alias: 'iraq|伊拉克|Ирак|irak|iraque|IRQ|IQ',
            phone: '964',
        },
        {
            name: 'Ireland - IE',
            code: 'IE',
            alias: 'ireland|爱尔兰|irlanda|Ирландия|irland|irlandia|irlande|ierland|アイルランド|아일랜드|IRL|IE',
            phone: '353',
        },
        {
            name: 'Isle of Man - IM',
            code: 'IM',
            alias: 'isle of man|曼恩岛|isla de man|Остров Мэн|isola di man|wyspa man|Île de man|man eiland|ilha de man|IMN|IM',
            phone: '44-1624',
        },
        {
            name: 'Israel - IL',
            code: 'IL',
            alias: 'israel|以色列|Израиль|israele|izrael|israël|イスラエル|이스라엘|ISR|IL',
            phone: '972',
        },
        {
            name: 'Italy - IT',
            code: 'IT',
            alias: 'italy|意大利|italia|Италия|italien|włochy|italie|italië|itália|イタリア|이탈리아|ITA|IT',
            phone: '39',
        },
        {
            name: 'Jamaica - JM',
            code: 'JM',
            alias: 'jamaica|牙买加|Ямайка|jamaika|giamaica|jamajka|jamaïque|JAM|JM',
            phone: '1-876',
        },
        {
            name: 'Japan - JP',
            code: 'JP',
            alias: 'japan|日本|japón|Япония|giappone|japonia|japon|일본|japão|japonya|JPN|JP',
            phone: '81',
        },
        {
            name: 'Jersey - JE',
            code: 'JE',
            alias: 'jersey|泽西岛|Джерси|JEY|JE',
            phone: '44-1534',
        },
        {
            name: 'Jordan - JO',
            code: 'JO',
            alias: 'jordan|约旦|jordania|Иордания|jordanien|giordania|jordanie|jordanië|요르단|ヨルダン|Ürdün|jordânia|JOR|JO',
            phone: '962',
        },
        {
            name: 'Kazakhstan - KZ',
            code: 'KZ',
            alias: 'kazakhstan|哈萨克斯坦|kazajistán|Казахстан|kazakistan|kazachstan|カザフスタン|카자흐스탄|KAZ|KZ',
            phone: '7',
        },
        {
            name: 'Kenya - KE',
            code: 'KE',
            alias: 'kenya|肯尼亚|kenia|Кения|케냐|ケニア|KEN|KE',
            phone: '254',
        },
        {
            name: 'Kiribati - KI',
            code: 'KI',
            alias: 'kiribati|基里巴斯|Кирибати|kirbati|KIR|KI',
            phone: '686',
        },
        {
            name: 'Kosovo - XK',
            code: 'XK',
            alias: 'kosovo|科索沃|Косово|kosowo|RKS|XK',
            phone: '383',
        },
        {
            name: 'Kuwait - KW',
            code: 'KW',
            alias: 'kuwait|科威特|Кувейт|kuwejt|koweit|koeweit|kuveyt|쿠웨이트|クウェート|KWT|KW',
            phone: '965',
        },
        {
            name: 'Kyrgyzstan - KG',
            code: 'KG',
            alias: 'kyrgyzstan|吉尔吉斯斯坦|kirguistán|Киргизстан|kirgisistan|kirgistan|kirghizistan|kirgizië|kırgızistan|kirgizistan|키르기스스탄|キルギスタン|quirguistão|KGZ|KG',
            phone: '996',
        },
        {
            name: 'Laos - LA',
            code: 'LA',
            alias: 'laos|Лаос|라오스|ラオス|老挝|LAO|LA',
            phone: '856',
        },
        {
            name: 'Latvia - LV',
            code: 'LV',
            alias: 'latvia|拉脱维亚|Латвия|lettland|lettonia|Łotwa|lettonie|letônia|letland|LVA|LV',
            phone: '371',
        },
        {
            name: 'Lebanon - LB',
            code: 'LB',
            alias: 'lebanon|黎巴嫩|libano|Ливан|libanon|liban|líbano|LBN|LB',
            phone: '961',
        },
        {
            name: 'Lesotho - LS',
            code: 'LS',
            alias: 'lesotho|莱索托|lesoto|Лесото|레소토|レソト|LSO|LS',
            phone: '266',
        },
        {
            name: 'Liberia - LR',
            code: 'LR',
            alias: 'liberia|利比里亚|Либерия|libéria|LBR|LR',
            phone: '231',
        },
        {
            name: 'Libya - LY',
            code: 'LY',
            alias: 'libya|利比亚|libia|Ливия|libyen|libye|líbia|libië|LBY|LY',
            phone: '218',
        },
        {
            name: 'Liechtenstein - LI',
            code: 'LI',
            alias: 'liechtenstein|列支敦士登|Лихтенштейн|LIE|LI',
            phone: '423',
        },
        {
            name: 'Lithuania - LT',
            code: 'LT',
            alias: 'lithuania|立陶宛|lituania|Литва|litauen|litwa|lituanie|lituânia|litouwen|リトアニア|리투아니아|LTU|LT',
            phone: '370',
        },
        {
            name: 'Luxembourg - LU',
            code: 'LU',
            alias: 'luxembourg|卢森堡|luxemburgo|Люксембург|luxemburg|lussemburgo|luksemburg|LUX|LU',
            phone: '352',
        },
        {
            name: 'Macao - MO',
            code: 'MO',
            alias: 'macao|澳门|Макао|makau|macau|マカオ|마카오|MAC|MO',
            phone: '853',
        },
        {
            name: 'Macedonia - MK',
            code: 'MK',
            alias: 'macedonia|Македония|makedonya|マケドニア|마케도니아|makedonien|macédoine|macedônia|mazedonien|macedonië|马其顿|MKD|MK',
            phone: '389',
        },
        {
            name: 'Madagascar - MG',
            code: 'MG',
            alias: 'madagascar|马达加斯加|Мадагаскар|madagaskar|madagáscar|마다가스카르|マダガスカル|MDG|MG',
            phone: '261',
        },
        {
            name: 'Malawi - MW',
            code: 'MW',
            alias: 'malawi|马拉维|Малави|malawai|말라위|マラウイ|malavi|MWI|MW',
            phone: '265',
        },
        {
            name: 'Malaysia - MY',
            code: 'MY',
            alias: 'malaysia|马来西亚|malasia|Малайзия|malaysien|malesia|malezja|malaysie|maleisië|malezya|말레이시아|マレーシア|malásia|MYS|MY',
            phone: '60',
        },
        {
            name: 'Maldives - MV',
            code: 'MV',
            alias: 'maldives|马尔代夫|maldivas|Мальдивы|malediven|maldive|malediwy|モルディブ|몰디브|MDV|MV',
            phone: '960',
        },
        {
            name: 'Mali - ML',
            code: 'ML',
            alias: 'mali|马里|Мали|MLI|ML',
            phone: '223',
        },
        {
            name: 'Malta - MT',
            code: 'MT',
            alias: 'malta|马耳他|Мальта|malte|MLT|MT',
            phone: '356',
        },
        {
            name: 'Marshall Islands - MH',
            code: 'MH',
            alias: 'marshall islands|马绍尔群岛|marshall (islas)|Маршалловы острова|marhsall inseln|isole marshall|wyspy marshalla|Îles marshall|marshalleilanden|ilhas marshall|MHL|MH',
            phone: '692',
        },
        {
            name: 'Martinique - MQ',
            code: 'MQ',
            alias: 'martinique|马提尼克|martinica|Мартиника|martynika|MTQ|MQ',
        },
        {
            name: 'Mauritania - MR',
            code: 'MR',
            alias: 'mauritania|毛里塔尼亚|Мавритания|mauretanien|mauretania|mauritanie|モーリタニア|mauritanië|MRT|MR',
            phone: '222',
        },
        {
            name: 'Mauritius - MU',
            code: 'MU',
            alias: 'mauritius|毛里求斯|mauricio|Маврикий|maurice|モーリシャス|MUS|MU',
            phone: '230',
        },
        {
            name: 'Mayotte - YT',
            code: 'YT',
            alias: 'mayotte|马约特|Майотта|majotta|マヨット|MYT|YT',
            phone: '262',
        },
        {
            name: 'Mexico - MX',
            code: 'MX',
            alias: 'mexico|墨西哥|méxico|Мексике|mexiko|messico|meksyk|mexique|meksika|멕시코|メキシコ|MEX|MX',
            phone: '52',
        },
        {
            name: 'Micronesia - FM',
            code: 'FM',
            alias: 'micronesia|密克罗尼西亚|Микронезия|mikronesien|mikronezja|micronésie|micronesië|FSM|FM',
            phone: '691',
        },
        {
            name: 'Moldova - MD',
            code: 'MD',
            alias: 'moldova|摩尔多瓦|moldavia|Молдова|moldavien|mołdawia|moldavie|moldavië|モルドバ|몰도바|moldávia|MDA|MD',
            phone: '373',
        },
        {
            name: 'Monaco - MC',
            code: 'MC',
            alias: 'monaco|摩纳哥|Монако|monako|MCO|MC',
            phone: '377',
        },
        {
            name: 'Mongolia - MN',
            code: 'MN',
            alias: 'mongolia|蒙古|Монголия|mongolei|mongolie|mongolië|MNG|MN',
            phone: '976',
        },
        {
            name: 'Montenegro - ME',
            code: 'ME',
            alias: 'montenegro|黑山|Черногория|czarnogóra|monténégro|MNE|ME',
            phone: '382',
        },
        {
            name: 'Montserrat - MS',
            code: 'MS',
            alias: 'montserrat|蒙特塞拉特|Монтсеррат|몬트세랫|モントセラト|MSR|MS',
            phone: '1-664',
        },
        {
            name: 'Morocco - MA',
            code: 'MA',
            alias: 'morocco|摩洛哥|marruecos|Марокко|marokko|marocco|maroko|maroc|모로코|モロッコ|MAR|MA',
            phone: '212',
        },
        {
            name: 'Mozambique - MZ',
            code: 'MZ',
            alias: 'mozambique|莫桑比克|Мозамбик|mozambico|mozambik|MOZ|MZ',
            phone: '258',
        },
        {
            name: 'Myanmar - MM',
            code: 'MM',
            alias: 'myanmar|缅甸|Мьянму|mjanma|미얀마|ミャンマー|MMR|MM',
            phone: '95',
        },
        {
            name: 'Namibia - NA',
            code: 'NA',
            alias: 'namibia|纳米比亚|Намибия|namibie|namibië|NAM|NA',
            phone: '264',
        },
        {
            name: 'Nauru - NR',
            code: 'NR',
            alias: 'nauru|瑙鲁|Науру|NRU|NR',
            phone: '674',
        },
        {
            name: 'Nepal - NP',
            code: 'NP',
            alias: 'nepal|尼泊尔|Непал|népal|NPL|NP',
            phone: '977',
        },
        {
            name: 'Netherlands - NL',
            code: 'NL',
            alias: 'netherlands|荷兰|paises bajos|Нидерланды|niederlande|olanda|holandia|pays-bas|nederland|países baixos|オランダ|네덜란드|NLD|NL',
            phone: '31',
        },
        {
            name: 'New Caledonia - NC',
            code: 'NC',
            alias: 'new caledonia|新喀里多尼亚|nueva caledonia|Новая Каледония|neukaledonien|nuova caledonia|nowa kaledonia|nouvelle-calédonie|nieuw-caledonië|nova caledônia|NCL|NC',
            phone: '687',
        },
        {
            name: 'New Zealand - NZ',
            code: 'NZ',
            alias: 'new zealand|新西兰|nueva zelanda|Новая Зеландия|neuseeland|nuova zelanda|nowa zelandia|nouvelle-zélande|nieuw-zeeland|yeni zelanda|nya zealand|뉴질랜드|ニュージーランド|nova zelândia|NZL|NZ',
            phone: '64',
        },
        {
            name: 'Nicaragua - NI',
            code: 'NI',
            alias: 'nicaragua|尼加拉瓜|Никарагуа|nikaragua|NIC|NI',
            phone: '505',
        },
        {
            name: 'Niger - NE',
            code: 'NE',
            alias: 'niger|尼日尔|Нигер|NER|NE',
            phone: '227',
        },
        {
            name: 'Nigeria - NG',
            code: 'NG',
            alias: 'nigeria|尼日利亚|Нигерия|nigerien|나이지리아|ナイジェリア|nijerya|NGA|NG',
            phone: '234',
        },
        {
            name: 'Niue - NU',
            code: 'NU',
            alias: 'niue|纽埃|Ниуэ|NIU|NU',
            phone: '683',
        },
        {
            name: 'Norfolk Island - NF',
            code: 'NF',
            alias: 'norfolk island|诺福克岛|norfolk (isla)|Остров Норфолк|norfolk inseln|isola di norfolk|wyspa norfolk|Île norfolk|norfolk eiland|ilha norfolk|NFK|NF',
        },
        {
            name: 'North Korea - KP',
            code: 'KP',
            alias: 'north korea|corea del norte|Северная Корея|kuzey kore|北朝鮮|북한|corea del nord|nordkorea|corée du nord|coréia do norte|noord-korea|korea północna|北朝鲜|PRK|KP',
            phone: '850',
        },
        {
            name: 'Northern Mariana Islands - MP',
            code: 'MP',
            alias: 'northern mariana islands|北马里亚纳群岛|marianas del norte (islas)|Северные Марианские Острова|nördliche mariana inseln|isole marianne settentrionali|mariany północne|Îles mariannes du nord|noorderlijke mariana eilanden|ilhas marianas do norte|MNP|MP',
            phone: '1-670',
        },
        {
            name: 'Norway - NO',
            code: 'NO',
            alias: 'norway|挪威|noruega|Норвегия|norwegen|norvegia|norwegia|norvège|noorwegen|ノルウェー|노르웨이|NOR|NO',
            phone: '47',
        },
        {
            name: 'Oman - OM',
            code: 'OM',
            alias: 'oman|阿曼|omán|Оман|umman|오만|オマーン|omã|OMN|OM',
            phone: '968',
        },
        {
            name: 'Pakistan - PK',
            code: 'PK',
            alias: 'pakistan|巴基斯坦|pakistán|Пакистан|파키스탄|パキスタン|paquistão|PAK|PK',
            phone: '92',
        },
        {
            name: 'Palau - PW',
            code: 'PW',
            alias: 'palau|帕劳|palaos|Палау|PLW|PW',
            phone: '680',
        },
        {
            name: 'Palestine - PS',
            code: 'PS',
            alias: 'palestine|palestina|Палестина|filistin|パレスチナ|팔레스타인|palästina|palestyna|巴勒斯坦|PSE|PS',
            phone: '970',
        },
        {
            name: 'Panama - PA',
            code: 'PA',
            alias: 'panama|巴拿马|panamá|Панама|PAN|PA',
            phone: '507',
        },
        {
            name: 'Papua New Guinea - PG',
            code: 'PG',
            alias: 'papua new guinea|巴布亚新几内亚|papua nueva guinea|Папуа-Новая Гвинея|papua-neuguinea|papua nuova guinea|papua nowa gwinea|papouasie-nouvelle-guinée|papoea-nieuw-guinea|パプアニューギニア|파푸아뉴기니|papua yeni gine|papua nya guinea|papua nova guiné|PNG|PG',
            phone: '675',
        },
        {
            name: 'Paraguay - PY',
            code: 'PY',
            alias: 'paraguay|巴拉圭|Парагвай|paragwaj|PRY|PY',
            phone: '595',
        },
        {
            name: 'Peru - PE',
            code: 'PE',
            alias: 'peru|秘鲁|perú|Перу|perù|pérou|ペルー|페루|PER|PE',
            phone: '51',
        },
        {
            name: 'Philippines - PH',
            code: 'PH',
            alias: 'philippines|菲律宾|filipinas|Филиппины|philippinen|filippine|filipiny|filipijnen|필리핀|フィリピン|filipinler|filippinerna|PHL|PH',
            phone: '63',
        },
        {
            name: 'Pitcairn - PN',
            code: 'PN',
            alias: 'pitcairn|皮特凯恩群岛|Острова Питкэрн|PCN|PN',
            phone: '64',
        },
        {
            name: 'Poland - PL',
            code: 'PL',
            alias: 'poland|波兰|polonia|Польша|polen|polska|pologne|polonya|ポーランド|폴란드|POL|PL',
            phone: '48',
        },
        {
            name: 'Portugal - PT',
            code: 'PT',
            alias: 'portugal|葡萄牙|Португалия|portogallo|portugalia|ポルトガル|포르투갈|PRT|PT',
            phone: '351',
        },
        {
            name: 'Puerto Rico - PR',
            code: 'PR',
            alias: 'puerto rico|波多黎各|Пуэрто-Рико|porto rico|portoryko|プエルトリコ|푸에르토 리코|PRI|PR',
            phone: '1-787, 1-939',
        },
        {
            name: 'Qatar - QA',
            code: 'QA',
            alias: 'qatar|卡塔尔|catar|Катар|katar|카타르|カタール|QAT|QA',
            phone: '974',
        },
        {
            name: 'Reunion - RE',
            code: 'RE',
            alias: 'reunion|留尼汪|reunión|Реюньон|wiedersehen|réunion|riunione|REU|RE',
            phone: '262',
        },
        {
            name: 'Romania - RO',
            code: 'RO',
            alias: 'romania|罗马尼亚|rumanía|Румыния|rumänien|rumunia|roumanie|roemenië|ルーマニア|루마니아|ROU|RO',
            phone: '40',
        },
        {
            name: 'Russia - RU',
            code: 'RU',
            alias: 'russia|俄罗斯|rusia|Россия|russland|rosja|russie|rusland|rusya|ryssland|러시아|ロシア|rússia|RUS|RU',
            phone: '7',
        },
        {
            name: 'Rwanda - RW',
            code: 'RW',
            alias: 'rwanda|卢旺达|ruanda|Руанда|르완다|ルワンダ|RWA|RW',
            phone: '250',
        },
        {
            name: 'Saint Barthelemy - BL',
            code: 'BL',
            alias: 'saint barthelemy|圣巴泰勒米岛|san bartolomé|Сен-Бартелеми|saint-barthelemy|saint-barthélémy|saint-barthélemy|BLM|BL',
            phone: '590',
        },
        {
            name: 'Saint Helena - SH',
            code: 'SH',
            alias: 'saint helena|santa helena|圣海伦娜|SHN|SH',
            phone: '290',
        },
        {
            name: 'Saint Kitts and Nevis - KN',
            code: 'KN',
            alias: 'saint kitts and nevis|圣基茨和尼维斯|san cristobal y nieves|Сент-Китс и Невис|saint kitts e nevis|saint kitts i nevis|세인트 키츠 네비스|セントクリストファーネイビス|KNA|KN',
            phone: '1-869',
        },
        {
            name: 'Saint Lucia - LC',
            code: 'LC',
            alias: 'saint lucia|圣卢西亚|santa lucía|Сент-Люсия|santa lucia|sainte-lucie|LCA|LC',
            phone: '1-758',
        },
        {
            name: 'Saint Martin - MF',
            code: 'MF',
            alias: 'saint martin|san martín|セント・マーチン|세인트 마틴|são martinho|saint-martin|st. martin|sint maarten|Сен-Мартен|圣马丁|MAF|MF',
            phone: '590',
        },
        {
            name: 'Saint Pierre and Miquelon - PM',
            code: 'PM',
            alias: 'saint pierre and miquelon|圣皮埃尔和密克隆|san pedro y miquelón|Сен-Пьер и Микелон|saint pierre und miquelon|saint pierre e miquelon|saint-pierre i miquelon|SPM|PM',
            phone: '508',
        },
        {
            name: 'Saint Vincent & Grenadines - VC',
            code: 'VC',
            alias: 'saint vincent & grenadines|圣文森特和格林纳丁斯|san vicente y las granadinas|VCT|VC',
            phone: '1-784',
        },
        {
            name: 'Samoa - WS',
            code: 'WS',
            alias: 'samoa|萨摩亚|Самоа|WSM|WS',
            phone: '685',
        },
        {
            name: 'San Marino - SM',
            code: 'SM',
            alias: 'san marino|圣马力诺|Сан-Марино|SMR|SM',
            phone: '378',
        },
        {
            name: 'Sao Tome & Principe - ST',
            code: 'ST',
            alias: 'sao tome & principe|santo tomé y príncipe|Сан-Томе И Принсипи|sao tome ve principe|サントメプリンシペ|상투메르핀시페|sao tome e principe|são tomé & príncipe|sao tomé-et-principe|são tomé & principe|sao tome en principe|wyspy Świętego tomasza i książęca|圣多美与普林西比|STP|ST',
            phone: '239',
        },
        {
            name: 'Saudi Arabia - SA',
            code: 'SA',
            alias: 'saudi arabia|沙特阿拉伯|arabia saudita|Саудовская Аравия|saudi arabien|arabia saudyjska|arabie saoudite|saoedi-arabië|사우디아라비아|サウジアラビア|suudi arabistan|arábia saudita|SAU|SA',
            phone: '966',
        },
        {
            name: 'Senegal - SN',
            code: 'SN',
            alias: 'senegal|塞内加尔|Сенегал|sénégal|SEN|SN',
            phone: '221',
        },
        {
            name: 'Serbia - RS',
            code: 'RS',
            alias: 'serbia|塞尔维亚|Сербия|serbien|serbie|servië|SRB|RS',
            phone: '381',
        },
        {
            name: 'Seychelles - SC',
            code: 'SC',
            alias: 'seychelles|塞舌尔|Сейшельские острова|seychellen|seszele|SYC|SC',
            phone: '248',
        },
        {
            name: 'Sierra Leone - SL',
            code: 'SL',
            alias: 'sierra leone|塞拉利昂|sierra leona|Сьерра-Леоне|シエラレオネ|시에라 리온|SLE|SL',
            phone: '232',
        },
        {
            name: 'Singapore - SG',
            code: 'SG',
            alias: 'singapore|新加坡|singapur|Сингапур|singapour|싱가포르|シンガポール|cingapura|SGP|SG',
            phone: '65',
        },
        {
            name: 'Sint Maarten - SX',
            code: 'SX',
            alias: 'sint maarten|Сен-Мартен|シントマールテン|신트마르턴|圣马丁|SXM|SX',
            phone: '1-721',
        },
        {
            name: 'Slovakia - SK',
            code: 'SK',
            alias: 'slovakia|斯洛伐克|eslovaquia|Словакия|slowakei|slovacchia|słowacja|slovaquie|slovakije|スロバキア|슬로바키아|SVK|SK',
            phone: '421',
        },
        {
            name: 'Slovenia - SI',
            code: 'SI',
            alias: 'slovenia|斯洛文尼亚|eslovenia|Словения|slowenien|słowenia|slovénie|slovenië|スロベニア|슬로베니아|SVN|SI',
            phone: '386',
        },
        {
            name: 'Solomon Islands - SB',
            code: 'SB',
            alias: 'solomon islands|所罗门群岛|islas salomón|Соломоновы острова|salomon inseln|isole salomone|wyspy salomona|Îles salomon|solomoneilanden|ソロモン諸島|솔로몬 제도|SLB|SB',
            phone: '677',
        },
        {
            name: 'Somalia - SO',
            code: 'SO',
            alias: 'somalia|索马里|Сомали|somalie|somalië|SOM|SO',
            phone: '252',
        },
        {
            name: 'South Africa - ZA',
            code: 'ZA',
            alias: 'south africa|南非|sudáfrica|Южная Африка|südafrika|sud africa|południowa afryka|afrique du sud|zuid-afrika|남아프리카|南アフリカ|güney afrika|sydafrika|África do sul|ZAF|ZA',
            phone: '27',
        },
        {
            name: 'South Georgia and the South Sandwich Islands - GS',
            code: 'GS',
            alias: 'south georgia and the south sandwich islands|南乔治亚和南桑德韦奇群岛|georgias del sur y sandwich del sur (islas)|Южная Георгия и Южные Сандвичевы Острова|südgeorgien und die südlichen sandwichinseln|georgia del sud e isole sandwich meridionali|georgia południowa i sandwich południowy|géorgie du sud et les îles sandwich du sud|zuid-georgia en de zuidelijke sandwicheilanden|SGS|GS',
        },
        {
            name: 'South Korea - KR',
            code: 'KR',
            alias: 'south korea|Южная Корея|güney kore|韓国|대한민국|corea del sud|sydkorea|corea del sur|corée du sud|südkorea|zuid-korea|korea południowa|coreia do sul|南韩|KOR|KR',
            phone: '82',
        },
        {
            name: 'South Sudan - SS',
            code: 'SS',
            alias: 'south sudan|南苏丹|sudán del sur|Южный Судан|südsudan|sudan del sud|sudan południowy|soudan du sud|zuid-soedan|SSD|SS',
            phone: '211',
        },
        {
            name: 'Spain - ES',
            code: 'ES',
            alias: 'spain|西班牙|españa|Испания|spanien|spagna|hiszpania|espagne|spanje|İspanya|espanha|スペイン|스페인|ESP|ES',
            phone: '34',
        },
        {
            name: 'Sri Lanka - LK',
            code: 'LK',
            alias: 'sri lanka|斯里兰卡|Шри-Ланка|스리랑카|スリランカ|LKA|LK',
            phone: '94',
        },
        {
            name: 'Sudan - SD',
            code: 'SD',
            alias: 'sudan|苏丹|sudán|Судан|soudan|soedan|SDN|SD',
            phone: '249',
        },
        {
            name: 'Suriname - SR',
            code: 'SR',
            alias: 'suriname|苏里南|surinam|Суринам|수리남|シンガポール|SUR|SR',
            phone: '597',
        },
        {
            name: 'Svalbard & Jan Mayen - SJ',
            code: 'SJ',
            alias: 'svalbard & jan mayen|Шпицберген и Ян-Майен|svalbard y jan mayen|svalbard ve jan mayen|スバールバル諸島＆ヤンマイエン島|스발바르 얀 마이엔|svalbard e jan mayen|svalbard et jan mayen|spitzbergen & jan mayen|svalbard en jan mayen|svalbard i jan mayen|斯瓦尔巴群岛和扬·马延|SJM|SJ',
            phone: '47',
        },
        {
            name: 'Swaziland - SZ',
            code: 'SZ',
            alias: 'swaziland|史瓦济兰|suazilandia|Свазиленд|suazi|SWZ|SZ',
            phone: '268',
        },
        {
            name: 'Sweden - SE',
            code: 'SE',
            alias: 'sweden|瑞典|suecia|Швеция|schweden|svezia|szwecja|suède|zweden|suécia|スウェーデン|스웨덴|SWE|SE',
            phone: '46',
        },
        {
            name: 'Switzerland - CH',
            code: 'CH',
            alias: 'switzerland|瑞士|suiza|Швейцария|schweiz|svizzera|szwajcaria|suisse|zwitserland|suíça|İsviçre|スイス|스위스|CHE|CH',
            phone: '41',
        },
        {
            name: 'Syria - SY',
            code: 'SY',
            alias: 'syria|叙利亚|siria|Сирия|syrien|syrie|syrië|síria|シリア|시리아|SYR|SY',
            phone: '963',
        },
        {
            name: 'Taiwan - TW',
            code: 'TW',
            alias: 'taiwan|台湾|taiwán|Тайвань|tajwan|taïwan|tayvan|대만|TWN|TW',
            phone: '886',
        },
        {
            name: 'Tajikistan - TJ',
            code: 'TJ',
            alias: 'tajikistan|塔吉克斯坦|tayikistán|Таджикистан|tadschikistan|tagikistan|tadżykistan|tadjikistan|tacikistan|타지키스탄|タジキスタン|tajiquistão|TJK|TJ',
            phone: '992',
        },
        {
            name: 'Tanzania - TZ',
            code: 'TZ',
            alias: 'tanzania|坦桑尼亚|Танзания|tansania|tanzanie|tanzanya|탄자니아|タンザニア|tanzânia|TZA|TZ',
            phone: '255',
        },
        {
            name: 'Thailand - TH',
            code: 'TH',
            alias: 'thailand|泰国|tailandia|ИЛИ|tajlandia|thaïlande|tayland|태국|タイ|tailândia|THA|TH',
            phone: '66',
        },
        {
            name: 'Togo - TG',
            code: 'TG',
            alias: 'togo|多哥|Того|TGO|TG',
            phone: '228',
        },
        {
            name: 'Tokelau - TK',
            code: 'TK',
            alias: 'tokelau|托克劳|Токелау|TKL|TK',
            phone: '690',
        },
        {
            name: 'Tonga - TO',
            code: 'TO',
            alias: 'tonga|汤加|Тонга|TON|TO',
            phone: '676',
        },
        {
            name: 'Trinidad and Tobago - TT',
            code: 'TT',
            alias: 'trinidad and tobago|特立尼达和多巴哥|trinidad y tobago|Тринидад и Тобаго|trinidad und tobago|trinidad e tobago|trinidad i tobago|trinidad et tobago|trinidad en tobago|TTO|TT',
            phone: '1-868',
        },
        {
            name: 'Tunisia - TN',
            code: 'TN',
            alias: 'tunisia|突尼斯|tunez|Тунис|tunesien|tunezja|tunisie|tunísia|tunesië|チュニジア|튀니지|TUN|TN',
            phone: '216',
        },
        {
            name: 'Turkey - TR',
            code: 'TR',
            alias: 'turkey|土耳其|turquía|Турция|türkei|turchia|turcja|turquie|turquia|turkije|türkiye|turkiet|터키|トルコ|TUR|TR',
            phone: '90',
        },
        {
            name: 'Turkmenistan - TM',
            code: 'TM',
            alias: 'turkmenistan|土库曼|Туркменистан|turkménistan|turcomenistão|TKM|TM',
            phone: '993',
        },
        {
            name: 'Turks & Caicos Islands - TC',
            code: 'TC',
            alias: 'turks & caicos islands|islas turcas y caicos|Острова Тёркс и Кайкос|turks ve caicos adaları|タークス＆カイコス諸島|터크스케이커스 제도|isole turks e caicos|turks & caicos-öarna|ilhas turcas e caicas|Îles turques-et-caïques|turks- und caicosinseln|turks en caicoseilanden|turks i caicos|特克斯和凯科斯群岛|TCA|TC',
            phone: '1-649',
        },
        {
            name: 'Tuvalu - TV',
            code: 'TV',
            alias: 'tuvalu|吐瓦鲁|Тувалу|TUV|TV',
            phone: '688',
        },
        {
            name: 'Uganda - UG',
            code: 'UG',
            alias: 'uganda|乌干达|Уганда|ouganda|oeganda|우간다|ウガンダ|UGA|UG',
            phone: '256',
        },
        {
            name: 'UK Virgin Islands - VG',
            code: 'VG',
            alias: 'uk virgin islands|islas vírgenes británicas|Британские Виргинские острова|birleşik krallık virgin adaları|イギリス領バージン諸島|uk 버진 아일랜드|isole vergini britanniche|brittiska jungfruöarna|ilhas virgens do reino unido|Îles vierges britanniques|britische jungferninseln|britse maagdeneilanden|brytyjskie wyspy dziewicze|英属维尔京群岛|VGB|VG',
            phone: '1-284',
        },
        {
            name: 'Ukraine - UA',
            code: 'UA',
            alias: 'ukraine|乌克兰|ucrania|Украина|ucraina|ukraina|ucrânia|oekraïne|ukrayna|우크라이나|ウクライナ|UKR|UA',
            phone: '380',
        },
        {
            name: 'United Arab Emirates - AE',
            code: 'AE',
            alias: 'united arab emirates|阿拉伯联合酋长国|emiratos Árabes unidos|Объединенные Арабские Эмираты|vereinigte arabische emirate|emirati arabi uniti|zjednoczone emiraty arabskie|Émirats arabes unis|emirados Árabes unidos|verenigde arabische emiraten|birleşik arap emirlikleri|förenta arab emiraten|아랍에미리트|アラブ首長国連邦|ARE|AE',
            phone: '971',
        },
        {
            name: 'United Kingdom - GB',
            code: 'GB',
            alias: 'united kingdom|uk|england|英国|reino unido|Великобритания|vereinigtes königreich|regno unito|wielka brytania|royaume-uni|verenigd koninkrijk|birleşik krallık|storbritannien|영국|イギリス|GBR|GB',
            phone: '44',
        },
        {
            name: 'United States - US',
            code: 'US',
            alias: "united states|usa|美国|estados unidos|Виза в США|vereinigte staaten|stati uniti d'america|stany zjednoczone|États-unis|verenigde staten|amerika birleşik devletleri|amerikas förenta stater|미국|アメリカ合衆国|USA|US",
            phone: '1',
        },
        {
            name: 'United States Minor Outlying Islands - UM',
            code: 'UM',
            alias: "united states minor outlying islands|美国本土外小岛屿|ultramarinas menores de ee.uu (islas)|Внешние малые острова США|vereinigte staaten minor outlying islands|isole minori esterne degli stati uniti d'america|dalekie wyspy mniejsze stanów zjednoczonych|Îles mineures éloignées des États-unis|ilhas menores distantes dos estados unidos|kleine afgelegen eilanden van de verenigde staten|UMI|UM",
        },
        {
            name: 'Uruguay - UY',
            code: 'UY',
            alias: 'uruguay|乌拉圭|Уругвай|urugwaj|uruguai|ウルグアイ|우루과이|URY|UY',
            phone: '598',
        },
        {
            name: 'US Virgin Islands - VI',
            code: 'VI',
            alias: 'us virgin islands|islas vírgenes de los estados unidos|Виргинские острова США|abd virgin adaları|アメリカ合衆国領バージン諸島|us 버진 아일랜드|isole vergini americane|amerikanska jungfruöarna|ilhas virgens dos estados unidos|Îles vierges des États-unis|us jungferninseln|amerikaanse maagdeneilanden|wyspy dziewicze stanów zjednoczonych|美属维尔京群岛|VIR|VI',
            phone: '1-340',
        },
        {
            name: 'Uzbekistan - UZ',
            code: 'UZ',
            alias: 'uzbekistan|乌兹别克斯坦|uzbekistán|Узбекистан|usbekistan|ouzbekistan|uzbequistão|ウズベキスタン|oezbekistan|Özbekistan|우즈베키스탄|UZB|UZ',
            phone: '998',
        },
        {
            name: 'Vanuatu - VU',
            code: 'VU',
            alias: 'vanuatu|瓦努阿图|Вануату|バヌアツ|VUT|VU',
            phone: '678',
        },
        {
            name: 'Vatican City - VA',
            code: 'VA',
            alias: 'vatican city|ciudad del vaticano|Ватикан|vatikan Şehri|バチカン市国|바티칸 시티|città del vaticano|vatikanstaten|cidade do vaticano|cité du vatican|vatikanstadt|vaticaan-stad|watykan|梵蒂冈城|VAT|VA',
            phone: '379',
        },
        {
            name: 'Venezuela - VE',
            code: 'VE',
            alias: 'venezuela|委内瑞拉|Венесуэла|wenezuela|ベネズエラ|VEN|VE',
            phone: '58',
        },
        {
            name: 'Vietnam - VN',
            code: 'VN',
            alias: 'vietnam|越南|Вьетнам|wietnam|viêt-nam|vietnã|ベトナム|베트남|VNM|VN',
            phone: '84',
        },
        {
            name: 'Wallis and Futuna - WF',
            code: 'WF',
            alias: 'wallis and futuna|瓦利斯和富图纳群岛|wallis y futuna|Уоллис и Футуна|wallis und futuna|wallis e futuna|wallis i futuna|wallis et futuna|wallis en futuna|ウォリス・フツナ諸島|WLF|WF',
            phone: '681',
        },
        {
            name: 'Western Sahara - EH',
            code: 'EH',
            alias: 'western sahara|西撒哈拉|sahara occidental|Западная Сахара|sahara occidentale|sahara zachodnia|saara ocidental|西サハラ|westelijke sahara|batı sahara|ESH|EH',
            phone: '212',
        },
        {
            name: 'Yemen - YE',
            code: 'YE',
            alias: 'yemen|也门|Йемен|jemen|yémen|iémen|イエメン|YEM|YE',
            phone: '967',
        },
        {
            name: 'Zambia - ZM',
            code: 'ZM',
            alias: 'zambia|赞比亚|Замбия|sambia|zambie|zâmbia|ザンビア|zambiya|잠비아|ZMB|ZM',
            phone: '260',
        },
        {
            name: 'Zimbabwe - ZW',
            code: 'ZW',
            alias: 'zimbabwe|津巴布韦|zimbabue|Зимбабве|zimbábue|ジンバブエ|zimbabve|짐바브웨|ZWE|ZW',
            phone: '263',
        },
    ],
};
